version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - image-data:/app/images
      - metadata:/app/metadata
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

volumes:
  image-data:
    name: replicator-images
  metadata:
    name: replicator-metadata